keyserv/views.py
# MIT License

# Copyright (c) 2019 Samuel Hoffman

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os

from flask import (Blueprint, abort, current_app, flash, redirect,
                   render_template, request, send_from_directory, url_for)
from flask_login import current_user, login_required, login_user, logout_user

from keyserv.auth import Users
from keyserv.forms import AppForm, KeyForm, LoginForm
from keyserv.keymanager import cut_key_unsafe
from keyserv.models import Application, AuditLog, Event, Key, db

frontend = Blueprint("frontend", __name__)


@frontend.route("/favicon.ico")
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, "static"),
                               "favicon.ico",
                               mimetype="image/vnd.microsoft.icon")


@frontend.route("/", methods=["GET", "POST"])
def index():

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate():
        current_app.logger.debug("login form was submitted")
        user = Users.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            if login_user(user):
                current_app.logger.debug(f"login for {user}")
        else:
            flash("Invalid username or password.", "error")
        return redirect(url_for("frontend.index"))

    return render_template("index.html", form=form, current_user=current_user)


@frontend.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("frontend.index"))


@frontend.route("/keys")
@login_required
def keys():
    return render_template("keys.html", keys=Key.query.all())


@frontend.route("/applications")
@login_required
def apps():
    return render_template("applications.html", apps=Application.query.all())


@frontend.route("/logs")
@login_required
def logs():
    return render_template("logs.html", logs=AuditLog.query.all())


@frontend.route("/modify/key/<int:key_id>", methods=["GET", "POST"])
@login_required
def modify_key(key_id: int):

    key = Key.query.get(key_id)
    if not key:
        abort(404)

    form = KeyForm(request.form)
    form.application.choices = [(app.id, app.name)
                                for app in Application.query.all()]

    if request.method == "POST" and form.validate_on_submit():
        changes = []

        if key.remaining != form.activations.data:
            changes.append(f"activations changed from {key.remaining}"
                           f" to {form.activations.data}")
            key.remaining = form.activations.data
        if key.memo != form.memo.data:
            changes.append(f"memo changed from {key.memo!r}"
                           f" to {form.memo.data!r}")
            key.memo = form.memo.data
        if key.app_id != form.application.data:
            changes.append(f"app changed from {key.app} to"
                           f" {form.application.data}")
            key.application = form.application.data
        if key.enabled != form.active.data:
            changes.append(f"active changed from {key.enabled}"
                           f" to {form.active.data}")
            key.enabled = form.active.data
        if key.hwid != form.hwid.data:
            changes.append(f"hwid changed from {key.hwid!r} to "
                           f"{form.hwid.data!r}")
            key.hwid = form.hwid.data

        AuditLog.from_key(key, f"edited by {current_user.username} "
                          f"({request.remote_addr}):"
                          f" {', '.join(changes)}", Event.KeyModified)

        try:
            db.session.commit()
            flash("Changes successful!")
            return redirect(url_for("frontend.detail_key", key_id=key.id))
        except Exception as error:
            flash(f"Failed to update key: {error}")

    form.application.data = key.app_id
    form.active.data = key.enabled
    form.memo.data = key.memo
    form.activations.data = key.remaining
    form.hwid.data = key.hwid

    return render_template("add_modify.html",
                           header=f"Modify Key {key.id}", form=form)


@frontend.route("/add/key", methods=["GET", "POST"])
@frontend.route("/add/key/<int:app_id>", methods=["GET", "POST"])
@login_required
def add_key(app_id=None):
    form = KeyForm(request.form)
    form.application.choices = [(app.id, app.name)
                                for app in Application.query.all()]

    if app_id:
        form.application.data = app_id

    if request.method == "POST" and form.validate_on_submit():
        try:
            token = cut_key_unsafe(form.activations.data,
                                   form.application.data,
                                   form.active.data, form.memo.data)
            flash(f"Key added! Token: {token}", "success")
        except Exception as error:
            flash(f"Unable to add key: {error}", "error")

    return render_template("add_modify.html", header="Add Key", form=form)


@frontend.route("/add/app", methods=["GET", "POST"])
@login_required
def add_app():
    form = AppForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        app = Application()
        app.name = form.name.data
        app.support_message = form.support.data

        db.session.add(app)
        try:
            db.session.commit()
            flash("Success!")
        except Exception as error:
            flash(f"Failed to add application: {error}")

    return render_template("add_modify.html",
                           form=form, header="Add Application")


@frontend.route("/modify/app/<int:app_id>", methods=["GET", "POST"])
@login_required
def modify_app(app_id: int):
    app = Application.query.get(app_id)

    if not app:
        abort(404)

    form = AppForm(request.form)
    if request.method == "POST" and form.validate_on_submit():

        app.name = form.name.data
        app.support_message = form.support.data
        try:
            db.session.commit()
            flash("Success.")
            return redirect(url_for("frontend.detail_app", app_id=app.id))
        except Exception as error:
            flash(f"Failed to modify application: {error}", "error")

    form.name.data = app.name
    form.support.data = app.support_message

    return render_template("add_modify.html", form=form)


@frontend.route("/detail/key/<int:key_id>")
@login_required
def detail_key(key_id: int):

    key = Key.query.get(key_id)

    if not key:
        abort(404)

    return render_template("detail_key.html", key=key)


@frontend.route("/detail/app/<int:app_id>")
@login_required
def detail_app(app_id: int):

    app = Application.query.get(app_id)

    if not app:
        abort(404)

    return render_template("detail_app.html", app=app)


@frontend.route("/keys/app/<int:app_id>")
@login_required
def keys_for_app(app_id):

    app = Application.query.get(app_id)

    if not app:
        abort(404)

    return render_template("keys.html", keys=app.keys)


@frontend.route("/keys/deactivate/<int:key_id>")
@login_required
def disable_key(key_id):

    key = Key.query.get(key_id)

    if not key:
        abort(404)

    key.enabled = False
    db.session.commit()

    return redirect(url_for("frontend.detail_key", key_id=key_id))


@frontend.route("/keys/activate/<int:key_id>")
@login_required
def enable_key(key_id):

    key = Key.query.get(key_id)

    if not key:
        abort(404)

    key.enabled = True
    db.session.commit()

    return redirect(url_for("frontend.detail_key", key_id=key_id))

keyserv/templates/add_modify.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}

{% block title %}Mini Key Server - {{ header }}{% endblock%}

{% block container %}
<h2>{{ header }}</h2>
{{ wtf.quick_form(form) }}
{%- endblock %}

keyserv/templates/applications.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}

{% block title %}Mini Key Server - Keys{% endblock%}

{% block container %}
<h2>Applications</h2>

<a href="{{ url_for('frontend.add_app') }}" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span> Add Application</a>


{% if apps %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Keys</th>
            <th>Support Message</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for app in apps %}
            <tr>
                <td>{{ app.id }}</td>
                <td>{{ app.name }}</td>
                <td>{{ app.keys|length }}</td>
                <td>{{ app.support_message }}</td>
                <td><a href="{{ url_for('frontend.modify_app', app_id=app.id) }}"
                       class="btn btn-info">
                        <span class="glyphicon glyphicon-edit"></span> Modify</a>
                    <a href="{{ url_for('frontend.detail_app', app_id=app.id) }}"
                        class="btn btn-primary">
                    <span class="glyphicon glyphicon-info-sign"></span> Detail</a>
                    </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="lead">No applications added. <a href="{{ url_for('frontend.add_app')}}">
    Add
</a> one to get started.</p>
{% endif %}
{%- endblock %}

keyserv/templates/detail_app.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}
{% extends "layout.html" %}

{% block title %}Mini Key Server - Application Detail{% endblock%}

{% block container %}
<h2>Detail for Application {{ app.name }}</h2>



<div class="panel panel-primary">

    <div class="panel-heading">{{ app.name }}</div>
        <div class="panel-body">
        <a href="{{ url_for('frontend.modify_app', app_id=app.id) }}" class="btn btn-info">
                <span class="glyphicon glyphicon-edit"></span> Modify</a>
        <a href="{{ url_for('frontend.add_key', app_id=app.id) }}" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span> Add Key</a>
        <br/><br/>
            <ul class="list-group">
                <li class="list-group-item"><b>App ID</b>: {{ app.id }}</li>
                <li class="list-group-item"><b>Number of Keys:</b> <a href="{{ url_for('frontend.keys_for_app', app_id=app.id) }}">{{ app.keys|length }}</a></li>
                <li class="list-group-item"><b>Support Message:</b> {{ app.support_message }}</li>
            </ul>
        </div>
</div>

<h3>Audit Log</h3>
<table class="table">
    <thead>
        <tr>
            <th>Key</th>
            <th>Time Stamp</th>
            <th>Message</th>
            <th>Event</th>
        </tr>
    </thead>
    <tbody>
        {% for log in app.logs|sort(attribute='id', reverse=True) %}
        <tr>
            <td><a href="{{ url_for('frontend.detail_key', key_id=log.key_id) }}">{{ log.key_id }}</a></td>
            <td>{{ log.timestamp.strftime("%Y-%m-%d %H:%M:%S") }}</td>
            <td>{{ log.message }}</td>
            <td>{{ log.event_type|event }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%- endblock %}

keyserv/templates/detail_key.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}
{% extends "layout.html" %}

{% block title %}Mini Key Server - Key Detail{% endblock%}

{% block container %}
<h2>Detail for Key {{ key.id }}</h2>

<div class="panel panel-primary">

    <div class="panel-heading">Key Info for {{ key.app.name }}</div>
        <div class="panel-body">
        <a href="{{ url_for('frontend.modify_key', key_id=key.id) }}" class="btn btn-info">
                <span class="glyphicon glyphicon-edit"></span> Modify</a>
        {% if key.enabled %}
        <a href="{{ url_for('frontend.disable_key', key_id=key.id) }}" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove"></span> Deactivate
        </a>
        {% else %}
        <a href="{{ url_for('frontend.enable_key', key_id=key.id) }}" class="btn btn-success">
                <span class="glyphicon glyphicon-ok-sign"></span> Activate</a>
        {% endif %}
        <br/><br/>
            <ul class="list-group">
                <li class="list-group-item"><b>Token:</b> <code>{{ key.token }}</code></li>
                <li class="list-group-item"><b>Active:</b> {{ "Yes" if key.enabled else "No" }}</li>
                <li class="list-group-item"><b>Remaining Activations:</b>
                {% if key.remaining == -1 %}
                Unlimited
                {% else %}
                {{ key.remaining }}
                {% endif %}</li>
                <li class="list-group-item"><b>Cut On:</b>
                    {{ key.cutdate|datetime }}</li>
                {% if key.memo %}
                <li class="list-group-item"><b>Memo:</b> {{ key.memo }}</li>
                {% endif %}
                <li class="list-group-item"><b>Lifetime Activations:</b>
                    {{ key.total_activations }}</li>

                {% if key.last_activation_ts %}
                <li class="list-group-item"><b>Last Activation</b> on
                    {{ key.last_activation_ts|datetime }} from
                    {{ key.last_activation_ip }}</li>
                {% endif %}


                <li class="list-group-item"><b>Hardware Id</b>:
                    {% if key.hwid %}
                    <code>{{ key.hwid }}</code>
                    {% else %}
                    ⚠️ No Hardware Id ⚠️
                    {% endif %}
                </li>

                <li class="list-group-item"><b>Lifetime Checks:</b> {{ key.total_checks }}</li>

                {% if key.last_check_ts %}
                <li class="list-group-item"><b>Last Check</b> on
                    {{ key.last_check_ts|datetime }} from
                    {{ key.last_check_ip }}</li>
                {% endif %}
            </ul>
        </div>
</div>

<h3>Audit Log</h3>
<table class="table">
    <thead>
        <tr>
            <th>Time Stamp</th>
            <th>Message</th>
            <th>Event</th>
        </tr>
    </thead>
    <tbody>
        {% for log in key.logs|sort(attribute='id', reverse=True) %}
        <tr>
            <td>{{ log.timestamp|datetime }}</td>
            <td>{{ log.message }}</td>
            <td>{{ log.event_type|event }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%- endblock %}

keyserv/templates/index.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}

{% import "bootstrap/wtf.html" as wtf %}
{% extends "layout.html" %}

{% block title %}Mini Key Server{% endblock%}

{% block container %}

{% if current_user.is_authenticated %}
<p>Currently signed in as
    <b>{{ current_user.username }}</b>
</p>
{% else %}
<p class="lead">Please login to continue.</p>
{{ wtf.quick_form(form) }} {% endif %}

{%- endblock %}

keyserv/templates/keys.html
{#
 MIT License

 Copyright(c) 2018 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}

{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "layout.html" %}

{% block title %}Mini Key Server - Keys{% endblock%}

{% block container %}
<h2>Keys</h2>
<a href="{{ url_for('frontend.add_key') }}" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span> Add Key</a>

{% if keys %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Token</th>
            <th>Application</th>
            <th>Active</th>
            <th>Remaining Activations</th>
            <th>Cut Date</th>
            <th>Memo</th>
            <th>Modify</th>
        </tr>
    </thead>
    <tbody>
        {% for key in keys %}
            <tr>
                <td>{{ key.id }}</td>
                <td><code>{{ key.token }}</code></td>
                <td> <a href="{{ url_for('frontend.detail_app', app_id=key.app.id) }}">{{ key.app.name }}</a></td>
                <td>{% if key.enabled %}Yes{% else %}No{% endif %}</td>
                <td>{% if key.remaining == -1 %}
                        Unlimited
                        {% else %}
                        {{ key.remaining }}
                        {% endif %}</td>
                <td>{{ key.cutdate.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>{{ key.memo }}</td>
                <td><a href="{{ url_for('frontend.modify_key', key_id=key.id) }}"
                       class="btn btn-info">
                        <span class="glyphicon glyphicon-edit"></span> Modify</a>

                    <a href="{{ url_for('frontend.detail_key', key_id=key.id) }}"
                       class="btn btn-primary">
                       <span class="glyphicon glyphicon-info-sign"></span> Detail</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="lead">No keys have been cut.</p>
{% endif %}
{%- endblock %}

keyserv/templates/layout.html
{#
 MIT License

 Copyright(c) 2019 Samuel Hoffman

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files(the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
#}

{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block title %}Mini Key Server{% endblock %}

{% block styles %} {{ super() }}
<link rel="icon" href="/favicon.ico?v=2"/>
{% endblock styles %}

{% block content %}
<!-- Copyright (c) 2018 Samuel Hoffman -->

<div class="container">
	<h1><img src="/static/icon.png" style="height: 40px;"> Mini Key Server</h1>
	<div class="row">
			<div class="col-md-12">
				{{ utils.flashed_messages(messages) }}
			</div>
		</div>
	{% if current_user.is_authenticated %}
	<a href="{{ url_for('frontend.keys') }}" class="btn btn-default">
		<span class="glyphicon glyphicon-lock"></span> Keys</a>
	<a href="{{ url_for('frontend.apps') }}" class="btn btn-default">
		<span class="glyphicon glyphicon-th"></span> Applications</a>
	<a href="{{ url_for('frontend.logs') }}" class="btn btn-default">
			<span class="glyphicon glyphicon-list"></span> Audit Log</a>
	<a href="{{ url_for('frontend.logout') }}" class="btn btn-danger">
			<span class="glyphicon glyphicon-log-out"></span> Log Out</a>
	<br/>
	{% endif %}
	{% block container %}{% endblock container %}
</div>
<footer class="container">
	<div class="container">
		<p class="text-muted">Copyright &copy; 2019, GliTch_ Is Mad Studios<br></p>
	</div>
</footer>
{% endblock %}